#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Harry Garrood"
email = "harry@garrood.me"

[templates]
git_push_bookmark = '"hdgarrood/push-" ++ change_id.short()'

[ui]
default-command = "log"

[revsets]
bookmark-advance-from = 'most_recent_bookmark(to)'
bookmark-advance-to = '@-'

[revset-aliases]
'most_recent_bookmark(x)' = 'heads(::x & bookmarks())'


[aliases]
prek = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj diff -r \"${1:-ancestors(@) ~ ancestors(trunk())}\" --name-only --no-pager | xargs prek run --files",
]
push = [ "git", "push", "-r", "'most_recent_bookmark(@-)'" ]

